apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: graph_weaver
  description: "Registered via the Add catalog-info.yaml template."
  annotations:
    github.com/project-slug: Gusto/graph_weaver
    gusto.com/service-tier: '1'
spec:
  type: library
  owner: team-embedded-devex
  lifecycle: stable
